# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Kouclo-live' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kouclo-live
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'SnapKit', '~> 3.1.2'
pod 'MJExtension', '~> 3.0.13'
pod 'LFLiveKit', '~> 2.5'
pod 'YYKit', '~> 1.0.9'
end
